package file_mode

const (
	READ        = 04
	WRITE       = 02
	EX          = 01
	USER_SHIFT  = 6
	GROUP_SHIFT = 3
	OTH_SHIFT   = 0

	USER_R   = READ << USER_SHIFT
	USER_W   = WRITE << USER_SHIFT
	USER_X   = EX << USER_SHIFT
	USER_RW  = USER_R | USER_W
	USER_RWX = USER_RW | USER_X

	GROUP_R   = READ << GROUP_SHIFT
	GROUP_W   = WRITE << GROUP_SHIFT
	GROUP_X   = EX << GROUP_SHIFT
	GROUP_RW  = GROUP_R | GROUP_W
	GROUP_RWX = GROUP_RW | GROUP_X

	OTH_R   = READ << OTH_SHIFT
	OTH_W   = WRITE << OTH_SHIFT
	OTH_X   = EX << OTH_SHIFT
	OTH_RW  = OTH_R | OTH_W
	OTH_RWX = OTH_RW | OTH_X

	ALL_R   = USER_R | GROUP_R | OTH_R
	ALL_W   = USER_W | GROUP_W | OTH_W
	ALL_X   = USER_X | GROUP_X | OTH_X
	ALL_RW  = ALL_R | ALL_W
	ALL_RWX = ALL_RW | GROUP_X
)
